apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmp-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /tmp
    type: Directory