apiVersion: v1
kind: Service
metadata:
  name: helloworld-k8s-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: helloworld-k8s
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30077