apiVersion: v1
kind: Service
metadata:
  name: helloworld-k8s-service
spec:
  type: NodePort
  selector:
    app: helloworld-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30003